language: python

python:
  - "2.7"

env:
  - VERSION="8.0" ODOO_REPO="odoo/odoo"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1"
  - VERSION="8.0" ODOO_REPO="oca/ocb"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/oca/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests ${VERSION}

after_success:
  coveralls